const CONSTANTS = {
	// Login request 
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',

	// global State
	GLOBAL_STATE_PERMISSION_REQUEST: 'GLOBAL_STATE_PERMISSION_REQUEST',
	GLOBAL_STATE_KEY_REQUEST: 'GLOBAL_STATE_KEY_REQUEST'
}
export default CONSTANTS
